sudo: false

language: php

php:
    - 7.1
    - 7.2
    - 7.3

cache:
    directories:
        - $HOME/.composer/cache/files

env:
    - SYMFONY_VERSION="^3.4.0"
    - SYMFONY_VERSION="4.0.*"
    - SYMFONY_VERSION="4.0.*" COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION="4.1.*"
    - SYMFONY_VERSION="4.1.*" COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION="4.2.*"
    - SYMFONY_VERSION="4.2.*" COMPOSER_FLAGS="--prefer-lowest"
    - SYMFONY_VERSION="4.3.*"
    - SYMFONY_VERSION="^4.3"
    
allow_failures:
    - env: SYMFONY_VERSION="^3.4.0"

matrix:
    fast_finish: true

before_install:
    - composer self-update
    - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-source

script:
    - vendor/bin/phpunit --colors
