sudo: false

language: php

cache:
    directories:
        - $HOME/.composer/cache/files

matrix:
    fast_finish: true
    include:
        - php: 7.1.33
          env:
            - SYMFONY_VERSION="^3.4.0"
            - SYMFONY_VERSION="^4.0"
            - SYMFONY_VERSION="^4.0" COMPOSER_FLAGS="--prefer-lowest"
            - SYMFONY_VERSION="^4.1"
            - SYMFONY_VERSION="^4.2"
            - SYMFONY_VERSION="^4.3"
            - SYMFONY_VERSION="^4.4"
            - SYMFONY_VERSION="^4.4" COMPOSER_FLAGS="--prefer-lowest"
            - SYMFONY_VERSION="^5.0"
            - SYMFONY_VERSION="dev"
        - php: 7.2
          env:
            - SYMFONY_VERSION="^3.4.0"
            - SYMFONY_VERSION="^4.0"
            - SYMFONY_VERSION="^4.0" COMPOSER_FLAGS="--prefer-lowest"
            - SYMFONY_VERSION="^4.1"
            - SYMFONY_VERSION="^4.2"
            - SYMFONY_VERSION="^4.3"
            - SYMFONY_VERSION="^4.4"
            - SYMFONY_VERSION="^4.4" COMPOSER_FLAGS="--prefer-lowest"
            - SYMFONY_VERSION="^5.0"
            - SYMFONY_VERSION="dev"
        - php: 7.3
          env:
            - SYMFONY_VERSION="^3.4.0"
            - SYMFONY_VERSION="^4.0"
            - SYMFONY_VERSION="^4.0" COMPOSER_FLAGS="--prefer-lowest"
            - SYMFONY_VERSION="^4.1"
            - SYMFONY_VERSION="^4.2"
            - SYMFONY_VERSION="^4.3"
            - SYMFONY_VERSION="^4.4"
            - SYMFONY_VERSION="^5.0"
            - SYMFONY_VERSION="dev"
    allow_failures:
        - php: 7.3
          env: SYMFONY_VERSION=dev
        - php: 7.3
          env: SYMFONY_VERSION="^5.0"

before_install:
    - composer self-update
    - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction  --prefer-stable

script:
    - vendor/bin/phpunit --colors
