sudo: false

language: php

cache:
    directories:
        - $HOME/.composer/cache/files

jobs:
    fast_finish: true
    include:
        - php: 7.3
          env: SYMFONY_VERSION="^4.4"

        - php: 7.3
          env: SYMFONY_VERSION="^5.0"

        - php: 7.3
          env: SYMFONY_VERSION="^5.0"

        - php: 7.4
          env: SYMFONY_VERSION="dev"

        - php: 7.4
          env: SYMFONY_VERSION="^5.1"
    allow_failures:
        - php: 7.4
          env: SYMFONY_VERSION="dev"

        - php: 7.4
          env: SYMFONY_VERSION="^5.1"
before_install:
    - composer self-update
    - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction  --prefer-stable

script:
    - vendor/bin/phpunit --colors
